FROM python

WORKDIR /app

COPY . /app

CMD [ "python", "rng.py" ]

# docker run -it {image_id} // Run interactive terminal
# docker start -ai {container_name} // Restart attached interactive container
