apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
  ports:
    - port:  80 # Local port
      targetPort: 8080 # container port
      protocol: TCP
  type: LoadBalancer

  # kubectl apply -f=service.yaml
  # kubectl get services        
  # kubectl expose second-app       
  # minikube service backend  